<?php
return array(
	'noticeCateId' => 94,
    'articleCateId' => 2,
    'videoCateId' => 82,
    'albumCateId' => 88,
    'symptomCateId' => 72,
    'fundCateId' => 3,
    
	'xuexiaoCateId' => 94,
    'xiaoxueCateId' => 191,
    'cuzhongCateId' => 192,
    'ditieCateId' => 104,
    'chaoxiangCateId' => 105,
    'zxcdCateId' => 106,
    'quyuCateId' => 107,
    'teseCateId' => 108,
    'shangquanCateId' => 190,
    'fwptCateId' => 195,
    'dianguiCateId' => 202,
    'youxiaoqiCateId' => 205,
    'kjylbCateId' => 210,
    'jianzhuleixinCateId' => 221,
    'zhuzhaileibieCateId' => 220,
    'fangwujiegouCateId' => 224,
    'chanquanxinzhiCateId' => 222,
    'kanfangshijianCateId' => 223,
    'fangwujiegouCateId' => 224,
    'fangyuanleixinCateId' => 241,
    'chuzufangshiCateId' => 242,
	
    'frontendId' => 'member',
    'permissionsTab' => 'sys_permissions',
    'groupPermissionsTab' => 'sys_group_priv',
);
?>
